[package]
name = "chaudloader-installer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "install"
path = "src/main.rs"

[dependencies]
steamlocate = "2"
anyhow = "1"
clap = { version = "4", features = ["derive"] }

[build-dependencies]
omnicopy_to_output = "0.3.0"
